apiVersion: v1
kind: Service
metadata:
  name: my-socket-server-service
spec:
  selector:
    app: my-socket-server
  ports:
    - protocol: TCP
      port: 65432
      targetPort: 65432
  type: LoadBalancer # Or NodePort for local clusters

